/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    skills: Skill;
    users: User;
    media: Media;
    projects: Project;
    services: Service;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills".
 */
export interface Skill {
  id: string;
  title?: string | null;
  description?: string | null;
  show?: boolean | null;
  showInDashboard?: boolean | null;
  featured?: boolean | null;
  url?: string | null;
  src?: string | null;
  mastery?: string | null;
  usage?: string | null;
  category?:
    | {
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  role: 'admin' | 'user';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  title?: string | null;
  description?: string | null;
  show?: boolean | null;
  showInDashboard?: boolean | null;
  featured?: boolean | null;
  gallery?:
    | {
        image: string;
        id?: string | null;
      }[]
    | null;
  body?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  slug?: string | null;
  category?:
    | {
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  stack?:
    | {
        title?: string | null;
        src?: string | null;
        id?: string | null;
      }[]
    | null;
  demo?:
    | {
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  sourcecode?:
    | {
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: string;
  title?: string | null;
  description?: string | null;
  show?: boolean | null;
  showInDashboard?: boolean | null;
  featured?: boolean | null;
  gallery?:
    | {
        image?: string | null;
        id?: string | null;
      }[]
    | null;
  body?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  icon?: string | null;
  url?: string | null;
  src?: string | null;
  types?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}

// declare module 'payload' {
//   export interface GeneratedTypes extends Config {}
// }
